### ISSUE TITLE
npm run devH5 报错

### ISSUE THREAD

**Issue by caorenjie** [Aimee1608/wxH5sudoku469#1]
TypeError: Cannot read property 'compile' of undefined
    at addCompilerHooks (F:\demo\wxH5sudoku469\node_modules\_webpack-dev-server@3.1.4@webpack-dev-server\lib\Server.js:7
1:16)
    at new Server (F:\demo\wxH5sudoku469\node_modules\_webpack-dev-server@3.1.4@webpack-dev-server\lib\Server.js:81:5)
    at startDevServer (F:\demo\wxH5sudoku469\node_modules\_webpack-dev-server@3.1.4@webpack-dev-server\bin\webpack-dev-s
erver.js:398:14)
    at processOptions (F:\demo\wxH5sudoku469\node_modules\_webpack-dev-server@3.1.4@webpack-dev-server\bin\webpack-dev-s
erver.js:361:5)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

**Comment by p0301y** [comment]
降级webpack-dev-server的版本，我试过了“^2.0.0”可用

**Comment by caorenjie** [comment]
感谢楼下，确实如此。

**Comment by caorenjie** [comment]
@p0301y   降级之后使用npm run build 后在小程序上报错，你有遇到吗

**Comment by Aimee1608** [comment]
仔细检查 安装的各个版本号啊 特别是 webpack 的版本

**Comment by JuniorZL** [comment]
通配符打包成小程序的时候会报错，怎么处理的呢？

**Comment by hawtim** [comment]
> 通配符打包成小程序的时候会报错，怎么处理的呢？

+1 同求解

**Comment by haoygit** [comment]
你好，你这个错解决了吗？我的降级了之后还是会报错
